<?php

return [

    'labels' => [
        'dashboard.view' => 'عرض الرئيسية',

        'hr.employees.view' => 'عرض الموظفين',
        'hr.employees.create' => 'إضافة موظف',
        'hr.employees.update' => 'تعديل موظف',
        'hr.employees.delete' => 'حذف موظف',
        'hr.salaries.view' => 'عرض الرواتب',
        'hr.salaries.manage' => 'إدارة الرواتب',

        'roles.view' => 'عرض الأدوار',
        'roles.create' => 'إنشاء دور',
        'roles.update' => 'تعديل دور',
        'roles.delete' => 'حذف دور',

        'structure.view' => 'عرض الهيكل التنظيمي',
        'structure.manage' => 'إدارة الهيكل التنظيمي',
        'structure.departments.view' => 'عرض الأقسام',
        'structure.departments.create' => 'إنشاء قسم',
        'structure.departments.update' => 'تعديل قسم',
        'structure.departments.delete' => 'حذف قسم',
        'structure.positions.manage' => 'إدارة بطاقات الوظائف',
        'structure.committees.manage' => 'إدارة اللجان',

        'projects.view' => 'عرض المشاريع',
        'projects.create' => 'إنشاء مشروع',
        'projects.update' => 'تعديل مشروع',
        'projects.delete' => 'حذف مشروع',
        'projects.programs.view' => 'عرض مكتبة البرامج',
        'projects.programs.manage' => 'إدارة البرامج وأسعارها',
        'projects.templates.manage' => 'إدارة قوالب الخطط',
        'projects.generate' => 'توليد المشاريع من الشراكات',
        'projects.visits.view' => 'عرض الزيارات والاستشارات',
        'projects.visits.manage' => 'إدارة الزيارات والاستشارات',
        'projects.measurement.view' => 'عرض القياس والأثر',
        'projects.measurement.manage' => 'إدارة القياس والأثر',
        'projects.close' => 'إغلاق المشاريع',

        'partnerships.view' => 'عرض الشراكات',
        'partnerships.create' => 'إنشاء شراكة',
        'partnerships.update' => 'تعديل شراكة',
        'partnerships.delete' => 'حذف شراكة',
        'partnerships.contracts.view' => 'عرض العقود',
        'partnerships.contracts.create' => 'إنشاء عقد',
        'partnerships.contracts.manage' => 'إدارة العقود',
        'partnerships.contracts.confirm' => 'تأكيد النسخة الموقعة (تعاقد)',
        'partnerships.organizations.view' => 'عرض الجهات الشريكة',
        'partnerships.organizations.manage' => 'إدارة الجهات الشريكة',
        'partnerships.pipeline.view' => 'عرض رحلة الشراكات',
        'partnerships.pipeline.manage' => 'نقل مراحل الشراكات',
        'partnerships.quotes.view' => 'عرض عروض الأسعار',
        'partnerships.quotes.create' => 'إنشاء عروض الأسعار',
        'partnerships.quotes.approve' => 'اعتماد عروض الأسعار',
        'partnerships.payments.view' => 'عرض دفعات الشراكات',
        'partnerships.payments.record' => 'تسجيل دفعات الشراكات',
        'partnerships.payments.confirm' => 'تأكيد المالية للدفعات',
        'partnerships.links.manage' => 'إدارة روابط الجهات',
        'partnerships.company-profile.manage' => 'إدارة بيانات الشركة',
        'partnerships.generate' => 'توليد مشروع من شراكة',

        'esnad.tasks.view' => 'عرض المهام',
        'esnad.tasks.team.view' => 'عرض مهام الفريق',
        'esnad.tasks.create' => 'إنشاء مهمة',
        'esnad.tasks.update' => 'تعديل مهمة',
        'esnad.tasks.delete' => 'حذف مهمة',

        'meetings.view' => 'عرض الاجتماعات',
        'meetings.create' => 'إنشاء اجتماع',
        'meetings.update' => 'تعديل اجتماع',
        'meetings.delete' => 'حذف اجتماع',

        'finance.expenses.view' => 'عرض المصروفات',
        'finance.expenses.create' => 'إنشاء طلب مصروف',
        'finance.expenses.approve' => 'اعتماد المصروفات',
        'finance.expenses.pay' => 'تنفيذ الدفع',
        'finance.payroll.view' => 'عرض مسيّرات الرواتب',
        'finance.payroll.approve' => 'اعتماد وتنفيذ الرواتب',
        'finance.custodies.view' => 'عرض العُهد',
        'finance.custodies.approve' => 'اعتماد العُهد',
        'finance.custodies.disburse' => 'صرف وتسوية العُهد',
        'finance.revenues.view' => 'عرض الإيرادات',
        'finance.revenues.manage' => 'إدارة الإيرادات',
        'finance.assets.view' => 'عرض الأصول',
        'finance.assets.manage' => 'إدارة الأصول',
        'finance.budgets.view' => 'عرض الموازنات',
        'finance.reports.view' => 'عرض التقارير المالية',
        'finance.tax_invoices.view' => 'عرض الفواتير الضريبية',
        'finance.tax_invoices.issue' => 'إصدار الفواتير والإشعارات الضريبية',

        'documents.view' => 'عرض المستندات',
        'documents.create' => 'رفع مستند',
        'documents.manage-versions' => 'إدارة نسخ المستندات',
        'documents.templates.manage' => 'إدارة مكتبة نماذج المستندات',
        'documents.policies.manage' => 'إدارة السياسات واللوائح',

        'reports.view' => 'عرض التقارير',
        'reports.weekly.view' => 'عرض التقرير الأسبوعي',
        'reports.monthly.view' => 'عرض التقرير الشهري',
        'reports.projects.view' => 'عرض تقارير المشاريع',
        'reports.impact.view' => 'عرض تقرير الأثر',
        'reports.kpis.view' => 'عرض مؤشرات الأداء',
        'reports.audit-log.view' => 'عرض سجل النشاط',
        'reports.export' => 'تصدير التقارير',

        'settings.manage' => 'إدارة إعدادات النظام',
        'settings.general.manage' => 'إدارة الإعدادات العامة',
        'settings.finance.manage' => 'إدارة إعدادات المالية',
        'settings.backup.manage' => 'إدارة النسخ الاحتياطي',
        'settings.notifications.manage' => 'إدارة إعدادات الإشعارات والبريد',
    ],

    'groups' => [
        'dashboard' => 'الرئيسية',
        'hr' => 'الموارد البشرية',
        'roles' => 'الأدوار والصلاحيات',
        'structure' => 'الهيكل التنظيمي',
        'projects' => 'المشاريع',
        'partnerships' => 'الشراكات',
        'esnad' => 'إسناد (المهام)',
        'meetings' => 'الاجتماعات',
        'finance' => 'المالية',
        'documents' => 'المستندات',
        'reports' => 'التقارير',
        'settings' => 'الإعدادات',
    ],

];
